Hw2
VladimirShat/Qt pull request #1
Opened 2020-03-27 18:50 UTC by VladimirShat

2020-03-27 20:15 UTC, tugolukovpn commented on Lesson3App&Net/QtNetwork/QtNetwork.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Добавить в исключения в .gitignore.

2020-03-27 20:15 UTC, tugolukovpn commented on Lesson3App&Net/QtNetwork/authmanager.cpp
> +            this -> authenticateError = reply -> errorString();
"this" не обязательно использовать.

2020-03-27 20:15 UTC, tugolukovpn commented on Lesson3App&Net/QtNetwork/authmanager.cpp
> +        this->onAuthenticateFinished();
Обработчик выполнения запроса уже есть. Еще один не нужен. Нужно либо слот использовать, либо лямбу.

2020-03-27 20:15 UTC, tugolukovpn commented on Lesson3App&Net/QtNetwork/authmanager.h
> +    QString authenticateError;
Публичные поля - нельзя. Нужны приватные поля. И геттеры для них.

2020-03-27 20:15 UTC, tugolukovpn commented on Lesson3App&Net/QtNetwork/authmanager.cpp
> +    qDebug() << "Auth error: " << this -> authenticateError;
Дебажный вывод надо выпилить.

2020-04-01 13:05 UTC, mashinapetro requested changes

2020-04-01 13:05 UTC, mashinapetro commented on Lesson3App&Net/QtNetwork/QtNetwork.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Файл нужно убрать под контроля git'а.

2020-04-01 13:05 UTC, mashinapetro commented on Lesson3App&Net/untitled/main.qml
> +                signUp.font.underline = false
Для подчеркивания надо использовать биндинг.

2020-04-01 13:05 UTC, mashinapetro commented on Lesson3App&Net/untitled/main.qml
> +                pageLoader.source = "qml/LoginForm.qml"
Для загрузки нужного компонента нужно использовать биндинг.

2020-04-01 13:05 UTC, mashinapetro commented on Lesson3App&Net/untitled/qml/Registration.qml
> +                loadingIndicatorOpacity.restart()
Если тебе в ветке "else" надо выполнить две команды, то надо использовать фигурные скобки.

2020-04-01 13:05 UTC, mashinapetro commented on Lesson3App&Net/untitled/untitled.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Файлы *.pro.user надо убрать из под контроля git'а.

2020-04-02 07:45 UTC, VladimirShat commented on Lesson3App&Net/QtNetwork/authmanager.cpp
> +            this -> authenticateError = reply -> errorString();
исправил

2020-04-02 07:45 UTC, VladimirShat commented on Lesson3App&Net/QtNetwork/QtNetwork.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
сделал, но не отсоединил уже присоединённые pro.user файлы

2020-04-02 07:46 UTC, VladimirShat commented on Lesson3App&Net/QtNetwork/authmanager.cpp
> +        this->onAuthenticateFinished();
исправил, слоты убрал, оставил лямбду

2020-04-02 07:46 UTC, wowa-shat commented on Lesson3App&Net/QtNetwork/authmanager.h
> +    QString authenticateError;
исправил

2020-04-02 07:46 UTC, VladimirShat commented on Lesson3App&Net/QtNetwork/authmanager.cpp
> +    qDebug() << "Auth error: " << this -> authenticateError;
выпилил

2020-04-02 07:47 UTC, VladimirShat commented on Lesson3App&Net/untitled/main.qml
> +                signUp.font.underline = false
сделал

2020-04-02 07:47 UTC, VladimirShat commented on Lesson3App&Net/untitled/main.qml
> +                pageLoader.source = "qml/LoginForm.qml"
сделал

2020-04-02 07:47 UTC, VladimirShat commented on Lesson3App&Net/untitled/qml/Registration.qml
> +                loadingIndicatorOpacity.restart()
добавил фигурные скобки

2020-04-02 07:48 UTC, VladimirShat commented on Lesson3App&Net/QtNetwork/QtNetwork.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
не смог убрать

2020-04-02 07:48 UTC, VladimirShat commented on Lesson3App&Net/untitled/untitled.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
не смог убрать

2020-04-02 09:05 UTC, tugolukovpn approved these changes

2020-04-02 09:15 UTC, merged